[package]
name = "lepatch"
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"

[dependencies]
bincode = "1.3.3"
fastcdc = "3.2.1"
fs2 = "0.4.3"
futures = "0.3.31"
serde = { version = "1.0.228", features = ["derive"] }
